# This is a basic workflow to help you get started with Actions

name: Third action (python)

# Controls when the workflow will run
on:
  # Makes the workflow run on each pull request
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "python"
  python:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4

      # Runs a single command using the runners shell
      - name: Run main.py
        run: python main.py

